name: Hello World

on:
  push:
    branches: ["main"]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "Github Actions will now run tests"

      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: install dep, run tests
        run: mvn test



