name: Run tests on schedule

on:
  schedule:
  #  - cron: "* 14 * * 1-5"
    - cron: "*/20 * * * 1-5" # Every 20 minut, weekdays
      # minute hour day-of-month month day-of-week

jobs:
  scheduled_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "Github Actions will now run tests on schedule every 20 mins"

      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: install dep, run tests
        run: mvn test



